---
- name: Install EPEL repository
  yum:
    name: epel-release
    state: present

- name: Install required packages for Provision (RHEL)
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "{{ provision_packages }}"
