---
- name: Create download directory for DR Provision
  file:
    path: "{{ provision_download_directory }}"
    state: directory
    mode: 0755

- name: Lookup DR Provision archive's checksum
  uri:
    url: "{{ provision_archive_checksum_url }}"
    return_content: yes
  register: __provision_checksum

- name: Fetch DR Provision artifacts
  get_url:
    url: "{{ provision_archive_url }}"
    dest: "{{ provision_download_directory }}/dr-provision.zip"
    checksum: "sha256:{{ __provision_checksum.content.split().0 }}"

- name: Extract DR Provision artifacts
  unarchive:
    src: "{{ provision_download_directory }}/dr-provision.zip"
    dest: "{{ provision_download_directory }}"
    remote_src: yes

- name: Install DR Provision binaries
  copy:
    src: "{{ provision_download_directory }}/bin/linux/{{ provision_architecture_map[ansible_architecture] }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    remote_src: yes
  with_items:
    - dr-provision
    - drpcli
  notify:
    - restart dr-provision
