---
- name: Install required packages for Provision (Alpine)
  apk:
    name: "{{ provision_packages | join(',') }}"
    state: present
    update_cache: yes

- name: import signing key
  get_url:
    url: https://raw.githubusercontent.com/sgerrand/alpine-pkg-glibc/master/sgerrand.rsa.pub
    dest: /etc/apk/keys/sgerrand.rsa.pub
    mode: 0440
  when: provision_glibc_environment
  ignore_errors: yes

- name: download glibc package
  get_url:
    url: "{{ glibc_package_url }}"
    dest: /tmp/glibc-2.26-r0.apk
    mode: 0644
  when: provision_glibc_environment
  ignore_errors: yes

- name: install glibc
  raw: apk add /tmp/glibc-2.26-r0.apk
  when: provision_glibc_environment
  ignore_errors: yes

- name: update all installed packages
  apk:
    upgrade: yes

- name: clean up cache packages
  raw: rm -rf /var/cache/apk/*
  ignore_errors: yes
