---
# tasks file for dr-provision
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"

- block:
  - name: DR Provision Dependencies Installation
    include_tasks: "install_packages_{{ ansible_pkg_mgr }}.yml"

  - name: DR Provision Installation
    include_tasks: install.yml

  - name: Start dr-provision
    include_tasks: service.yml

  - name: Setup dr-provision
    include_tasks: setup.yml
  when: not provision_clean

- name: Clean dr-provision
  include_tasks: clean.yml
  when: provision_clean
