---
- block:
  - name: Install systemd unit file for DR Provision
    template:
      src: dr-provision.service
      dest: /lib/systemd/system/dr-provision.service
    register: __provision_systemd_unit_file
    notify:
      - restart dr-provision

  - name: Reload systemd if DR Provision unit file has changed
    systemd:
      daemon_reload: yes
    when: __provision_systemd_unit_file is changed
  when: 'ansible_service_mgr == "systemd"'

- name: Install OpenRC init script for DR Provision
  template:
    src: dr-provision.openrc
    dest: /etc/init.d/dr-provision
    mode: 0755
  when: 'ansible_service_mgr == "openrc"'
  notify:
    - restart dr-provision

- name: Start and enable DR Provision
  service:
    name: dr-provision
    state: started
    enabled: yes
